version: '2'

services:
  nginx:
    image: nginx:1-alpine
    volumes:
      - ./build/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80
    depends_on:
      - node

  node: 
    image: node:7.5-alpine
    volumes:
      - ./:/code/
    working_dir: /code/
    entrypoint: 'npm start'
